import PDFDocument from "pdfkit";
import { computeSha256 } from "./storage";

// ─── Types ───────────────────────────────────────────────────

interface FlaggedLineItem {
  description: string;
  amount: number;
  flag: string;
  flagNote: string | null;
  clause: {
    clauseRef: string | null;
    title: string;
    type: string | null;
    value: number | null;
  } | null;
  change: {
    sequenceNum: number;
    title: string;
    status: string;
    estimatedImpact: number | null;
  } | null;
}

interface DisputePdfOptions {
  programName: string;
  cdmoName: string;
  invoiceNumber: string | null;
  invoiceDate: Date | null;
  vendorName: string | null;
  currency: string;
  totalAmount: number | null;
  generatedBy: string;
  flaggedItems: FlaggedLineItem[];
  orgName?: string;
  logoBuffer?: Buffer;
}

// ─── Constants ───────────────────────────────────────────────

const C = {
  navy: "#1a2332",
  dark: "#222222",
  mid: "#555555",
  muted: "#888888",
  light: "#f5f5f5",
  border: "#dddddd",
  white: "#ffffff",
  red: "#dc2626",
  redBg: "#fef2f2",
  amber: "#d97706",
  amberBg: "#fffbeb",
  green: "#059669",
  greenBg: "#f0fdf4",
  blue: "#2563eb",
  blueBg: "#eff6ff",
} as const;

const FLAG_LABELS: Record<string, string> = {
  RATE_MISMATCH: "Rate Mismatch",
  SCOPE_CREEP: "Scope Creep",
  UNAPPROVED_CHANGE: "Unapproved Change",
  DUPLICATE: "Duplicate",
  MISSING_BASELINE: "Missing Baseline",
  ASSUMPTION_VIOLATION: "Assumption Violation",
  OTHER: "Other",
};

const FLAG_COLORS: Record<string, { bg: string; text: string }> = {
  RATE_MISMATCH: { bg: C.redBg, text: C.red },
  SCOPE_CREEP: { bg: C.redBg, text: C.red },
  UNAPPROVED_CHANGE: { bg: C.amberBg, text: C.amber },
  DUPLICATE: { bg: C.amberBg, text: C.amber },
  MISSING_BASELINE: { bg: C.amberBg, text: C.amber },
  ASSUMPTION_VIOLATION: { bg: C.redBg, text: C.red },
  OTHER: { bg: C.light, text: C.mid },
};

const PAGE_W = 595.28; // A4
const PAGE_H = 841.89;
const MARGIN = 50;
const USABLE_W = PAGE_W - 2 * MARGIN;
const FOOTER_Y = PAGE_H - 40;

function fmt(n: number, currency: string): string {
  return `${currency} ${n.toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}

// ─── Main Export ─────────────────────────────────────────────

export async function generateDisputePdf(
  options: DisputePdfOptions
): Promise<{ buffer: Buffer; sha256Hash: string }> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: MARGIN,
      bufferPages: true,
      info: { Title: "Forensic Dispute Packet", Author: "CGT Sync" },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => {
      const buffer = Buffer.concat(chunks);
      const sha256Hash = computeSha256(buffer);
      resolve({ buffer, sha256Hash });
    });
    doc.on("error", reject);

    const items = options.flaggedItems;
    const totalDisputed = items.reduce((s, i) => s + i.amount, 0);
    const flagCounts: Record<string, number> = {};
    let highestVariancePct = 0;
    for (const item of items) {
      flagCounts[item.flag] = (flagCounts[item.flag] ?? 0) + 1;
      if (item.clause?.value && item.clause.value !== 0) {
        const pct = Math.abs((item.amount - item.clause.value) / item.clause.value) * 100;
        if (pct > highestVariancePct) highestVariancePct = pct;
      }
    }

    // ──── PAGE 1: Cover + Executive Summary ────

    // Header bar
    doc.rect(0, 0, PAGE_W, 70).fill(C.navy);
    let headerTextX = MARGIN;
    if (options.logoBuffer) {
      try {
        doc.image(options.logoBuffer, MARGIN, 18, { width: 30 });
        headerTextX = MARGIN + 38;
      } catch {
        // skip logo on error
      }
    }
    doc.fontSize(18).fillColor(C.white).text("FORENSIC DISPUTE PACKET", headerTextX, 22, { width: USABLE_W - (headerTextX - MARGIN) });
    const headerLabel = options.orgName ? `CGT Sync | ${options.orgName} | Confidential` : "CGT Sync | Confidential";
    doc.fontSize(8).fillColor("#aabbcc").text(headerLabel, MARGIN, 48, { width: USABLE_W, align: "left" });
    doc.text(`Generated: ${new Date().toISOString().split("T")[0]}`, MARGIN, 48, { width: USABLE_W, align: "right" });

    // Program / Invoice info
    doc.fillColor(C.dark);
    let y = 90;
    doc.fontSize(11).text(options.programName, MARGIN, y);
    y += 16;
    doc.fontSize(9).fillColor(C.mid).text(`CDMO: ${options.cdmoName}`, MARGIN, y);
    y += 14;

    const infoRows = [
      ["Invoice #", options.invoiceNumber ?? "N/A"],
      ["Vendor", options.vendorName ?? "N/A"],
      ["Invoice Date", options.invoiceDate ? new Date(options.invoiceDate).toLocaleDateString() : "N/A"],
      ["Invoice Total", options.totalAmount != null ? fmt(options.totalAmount, options.currency) : "N/A"],
      ["Generated By", options.generatedBy],
    ];
    for (const [label, value] of infoRows) {
      doc.fontSize(8).fillColor(C.muted).text(`${label}:`, MARGIN, y, { continued: true });
      doc.fillColor(C.dark).text(`  ${value}`);
      y += 13;
    }

    y += 10;
    // Separator
    doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).strokeColor(C.border).stroke();
    y += 15;

    // ──── Executive Summary Metrics ────
    doc.fontSize(12).fillColor(C.dark).text("Executive Summary", MARGIN, y);
    y += 22;

    const metricBoxW = (USABLE_W - 15) / 4;
    const metricBoxH = 52;
    const metrics = [
      { label: "Total Disputed", value: fmt(totalDisputed, options.currency), bg: C.redBg, text: C.red },
      { label: "Flagged Items", value: String(items.length), bg: C.amberBg, text: C.amber },
      { label: "Highest Variance", value: highestVariancePct > 0 ? `${highestVariancePct.toFixed(1)}%` : "N/A", bg: C.redBg, text: C.red },
      { label: "Invoice Total", value: options.totalAmount != null ? fmt(options.totalAmount, options.currency) : "N/A", bg: C.blueBg, text: C.blue },
    ];
    for (let i = 0; i < metrics.length; i++) {
      const mx = MARGIN + i * (metricBoxW + 5);
      doc.roundedRect(mx, y, metricBoxW, metricBoxH, 4).fill(metrics[i].bg);
      doc.fontSize(7).fillColor(C.muted).text(metrics[i].label.toUpperCase(), mx + 8, y + 8, { width: metricBoxW - 16 });
      doc.fontSize(14).fillColor(metrics[i].text).text(metrics[i].value, mx + 8, y + 24, { width: metricBoxW - 16 });
    }
    y += metricBoxH + 15;

    // ──── Flag Distribution ────
    doc.fontSize(10).fillColor(C.dark).text("Flag Distribution", MARGIN, y);
    y += 16;
    for (const [flag, count] of Object.entries(flagCounts)) {
      const colors = FLAG_COLORS[flag] ?? { bg: C.light, text: C.mid };
      doc.roundedRect(MARGIN, y, 8, 8, 2).fill(colors.text);
      doc.fontSize(8).fillColor(C.dark).text(`${FLAG_LABELS[flag] ?? flag}: ${count}`, MARGIN + 14, y - 1);
      y += 14;
    }

    y += 15;
    doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).strokeColor(C.border).stroke();
    y += 15;

    // ──── Flagged Items Summary Table ────
    doc.fontSize(12).fillColor(C.dark).text("Flagged Items Summary", MARGIN, y);
    y += 20;

    // Table header
    const cols = [
      { label: "#", w: 25 },
      { label: "Description", w: 170 },
      { label: "Amount", w: 80 },
      { label: "Flag", w: 85 },
      { label: "Baseline / CO Ref", w: 100 },
      { label: "Variance", w: USABLE_W - 25 - 170 - 80 - 85 - 100 },
    ];

    function drawTableHeader(yPos: number): number {
      doc.rect(MARGIN, yPos, USABLE_W, 18).fill(C.navy);
      let cx = MARGIN;
      for (const col of cols) {
        doc.fontSize(7).fillColor(C.white).text(col.label, cx + 4, yPos + 5, { width: col.w - 8 });
        cx += col.w;
      }
      return yPos + 18;
    }

    y = drawTableHeader(y);

    for (let i = 0; i < items.length; i++) {
      const item = items[i];
      // Page break check
      if (y + 20 > FOOTER_Y - 30) {
        doc.addPage();
        y = MARGIN;
        y = drawTableHeader(y);
      }

      const rowBg = i % 2 === 0 ? C.white : C.light;
      doc.rect(MARGIN, y, USABLE_W, 18).fill(rowBg);

      let cx = MARGIN;
      const rowY = y + 5;

      // #
      doc.fontSize(7).fillColor(C.dark).text(String(i + 1), cx + 4, rowY, { width: cols[0].w - 8 });
      cx += cols[0].w;

      // Description
      const desc = item.description.length > 40 ? item.description.slice(0, 40) + "..." : item.description;
      doc.fontSize(7).fillColor(C.dark).text(desc, cx + 4, rowY, { width: cols[1].w - 8 });
      cx += cols[1].w;

      // Amount
      doc.fontSize(7).fillColor(C.dark).text(fmt(item.amount, options.currency), cx + 4, rowY, { width: cols[2].w - 8 });
      cx += cols[2].w;

      // Flag
      const flagColors = FLAG_COLORS[item.flag] ?? { bg: C.light, text: C.mid };
      doc.roundedRect(cx + 3, y + 3, cols[3].w - 6, 12, 2).fill(flagColors.bg);
      doc.fontSize(6).fillColor(flagColors.text).text(FLAG_LABELS[item.flag] ?? item.flag, cx + 6, rowY, { width: cols[3].w - 12 });
      cx += cols[3].w;

      // Baseline / CO Ref
      let ref = "—";
      if (item.clause) ref = item.clause.clauseRef ?? item.clause.title;
      else if (item.change) ref = `CO #${item.change.sequenceNum}`;
      doc.fontSize(7).fillColor(C.mid).text(ref.length > 20 ? ref.slice(0, 20) + "..." : ref, cx + 4, rowY, { width: cols[4].w - 8 });
      cx += cols[4].w;

      // Variance
      let variance = "—";
      if (item.clause?.value != null && item.clause.value !== 0) {
        const diff = item.amount - item.clause.value;
        const pct = (diff / Math.abs(item.clause.value)) * 100;
        variance = `${diff >= 0 ? "+" : ""}${fmt(diff, options.currency)} (${pct >= 0 ? "+" : ""}${pct.toFixed(1)}%)`;
      }
      const varianceColor = variance.startsWith("+") ? C.red : variance === "—" ? C.muted : C.green;
      doc.fontSize(7).fillColor(varianceColor).text(variance, cx + 4, rowY, { width: cols[5].w - 8 });

      y += 18;
    }

    // ──── Individual Item Details ────
    y += 20;
    if (y + 40 > FOOTER_Y - 30) {
      doc.addPage();
      y = MARGIN;
    }

    doc.fontSize(12).fillColor(C.dark).text("Detailed Item Analysis", MARGIN, y);
    y += 22;

    for (let i = 0; i < items.length; i++) {
      const item = items[i];

      // Page break check — need at least 130pt for an item detail block
      if (y + 130 > FOOTER_Y - 10) {
        doc.addPage();
        y = MARGIN;
      }

      // Item header with flag badge
      const flagColors = FLAG_COLORS[item.flag] ?? { bg: C.light, text: C.mid };
      doc.roundedRect(MARGIN, y, USABLE_W, 22, 4).fill(C.light);
      doc.fontSize(9).fillColor(C.dark).text(`Item ${i + 1}`, MARGIN + 8, y + 6);
      // Flag pill
      const flagLabel = FLAG_LABELS[item.flag] ?? item.flag;
      const flagPillW = doc.widthOfString(flagLabel) + 16;
      doc.roundedRect(MARGIN + 60, y + 3, flagPillW, 16, 8).fill(flagColors.bg);
      doc.fontSize(7).fillColor(flagColors.text).text(flagLabel, MARGIN + 68, y + 7);
      y += 30;

      // Description
      doc.fontSize(8).fillColor(C.muted).text("DESCRIPTION", MARGIN, y);
      y += 11;
      doc.fontSize(9).fillColor(C.dark).text(item.description, MARGIN, y, { width: USABLE_W });
      y += doc.heightOfString(item.description, { width: USABLE_W }) + 8;

      // Two-column: Invoice Data | Truth Source
      const colW = (USABLE_W - 20) / 2;
      const leftX = MARGIN;
      const rightX = MARGIN + colW + 20;
      const twoColY = y;

      // Left column: Invoice Data
      doc.rect(leftX, twoColY, colW, 60).fillAndStroke(C.light, C.border);
      doc.fontSize(7).fillColor(C.muted).text("INVOICE DATA", leftX + 8, twoColY + 6, { width: colW - 16 });
      doc.fontSize(9).fillColor(C.dark).text(`Amount: ${fmt(item.amount, options.currency)}`, leftX + 8, twoColY + 20, { width: colW - 16 });
      if (item.flagNote) {
        doc.fontSize(7).fillColor(C.red).text(`Note: ${item.flagNote}`, leftX + 8, twoColY + 36, { width: colW - 16 });
      }

      // Right column: Truth Source
      if (item.clause) {
        doc.rect(rightX, twoColY, colW, 60).fillAndStroke(C.blueBg, C.border);
        doc.fontSize(7).fillColor(C.blue).text("SOW BASELINE CLAUSE", rightX + 8, twoColY + 6, { width: colW - 16 });
        const clauseLabel = item.clause.clauseRef ? `${item.clause.clauseRef}: ${item.clause.title}` : item.clause.title;
        doc.fontSize(8).fillColor(C.dark).text(clauseLabel, rightX + 8, twoColY + 20, { width: colW - 16 });
        if (item.clause.value != null) {
          doc.fontSize(9).fillColor(C.dark).text(`Baseline: ${fmt(item.clause.value, options.currency)}`, rightX + 8, twoColY + 36, { width: colW - 16 });
        }
        if (item.clause.type) {
          doc.fontSize(7).fillColor(C.muted).text(`Type: ${item.clause.type}`, rightX + 8, twoColY + 48, { width: colW - 16 });
        }
      } else if (item.change) {
        doc.rect(rightX, twoColY, colW, 60).fillAndStroke("#faf5ff", C.border);
        doc.fontSize(7).fillColor("#7c3aed").text("CHANGE ORDER", rightX + 8, twoColY + 6, { width: colW - 16 });
        doc.fontSize(8).fillColor(C.dark).text(`#${item.change.sequenceNum}: ${item.change.title}`, rightX + 8, twoColY + 20, { width: colW - 16 });
        doc.fontSize(8).fillColor(C.dark).text(`Status: ${item.change.status}`, rightX + 8, twoColY + 36, { width: colW - 16 });
        if (item.change.estimatedImpact != null) {
          doc.fontSize(9).fillColor(C.dark).text(`Impact: ${fmt(item.change.estimatedImpact, options.currency)}`, rightX + 8, twoColY + 48, { width: colW - 16 });
        }
      } else {
        doc.rect(rightX, twoColY, colW, 60).fillAndStroke(C.amberBg, C.border);
        doc.fontSize(7).fillColor(C.amber).text("NO TRUTH SOURCE", rightX + 8, twoColY + 6, { width: colW - 16 });
        doc.fontSize(8).fillColor(C.dark).text("No matching baseline clause or confirmed change order found.", rightX + 8, twoColY + 20, { width: colW - 16 });
      }
      y = twoColY + 68;

      // Variance box (only if clause with value)
      if (item.clause?.value != null && item.clause.value !== 0) {
        const diff = item.amount - item.clause.value;
        const pct = (diff / Math.abs(item.clause.value)) * 100;
        const isOver = Math.abs(pct) > 5;
        const vBg = isOver ? C.redBg : C.greenBg;
        const vText = isOver ? C.red : C.green;

        doc.roundedRect(MARGIN, y, USABLE_W, 24, 4).fill(vBg);
        doc.fontSize(8).fillColor(vText).text(
          `Variance: ${diff >= 0 ? "+" : ""}${fmt(diff, options.currency)} (${pct >= 0 ? "+" : ""}${pct.toFixed(1)}%)${isOver ? " — Exceeds 5% threshold" : " — Within threshold"}`,
          MARGIN + 8,
          y + 7,
          { width: USABLE_W - 16 }
        );
        y += 32;
      }

      y += 10;
    }

    // ──── Footer on every page ────
    const pageRange = doc.bufferedPageRange();
    const totalPages = pageRange.count;
    const docId = `DOC-${Date.now()}`;
    for (let i = 0; i < totalPages; i++) {
      doc.switchToPage(i);
      // Bottom line
      doc.moveTo(MARGIN, FOOTER_Y - 5).lineTo(PAGE_W - MARGIN, FOOTER_Y - 5).strokeColor(C.border).stroke();
      doc.fontSize(7).fillColor(C.muted).text(
        `Page ${i + 1} of ${totalPages}`,
        MARGIN,
        FOOTER_Y,
        { width: USABLE_W / 3 }
      );
      doc.fontSize(7).fillColor(C.muted).text(
        "CGT Sync | Confidential — For Dispute Purposes Only",
        MARGIN + USABLE_W / 3,
        FOOTER_Y,
        { width: USABLE_W / 3, align: "center" }
      );
      doc.fontSize(7).fillColor(C.muted).text(
        `SHA-256: see filename | ${docId}`,
        MARGIN + (2 * USABLE_W) / 3,
        FOOTER_Y,
        { width: USABLE_W / 3, align: "right" }
      );
    }

    doc.end();
  });
}
