import PDFDocument from "pdfkit";
import { computeSha256 } from "./storage";

// ─── Constants ───────────────────────────────────────────────

const PAGE_W = 595.28; // A4
const PAGE_H = 841.89;
const MARGIN = 50;
const USABLE_W = PAGE_W - 2 * MARGIN;
const FOOTER_Y = PAGE_H - 40;

// ─── Types ───────────────────────────────────────────────────

interface PdfSection {
  title: string;
  rows: { label: string; value: string }[];
}

interface PdfOptions {
  title: string;
  subtitle?: string;
  generatedBy?: string;
  sections: PdfSection[];
  footer?: string;
  orgName?: string;
  logoBuffer?: Buffer;
}

// ─── drawTable ───────────────────────────────────────────────

export function drawTable(
  doc: InstanceType<typeof PDFDocument>,
  headers: { label: string; width: number; align?: "left" | "right" | "center" }[],
  rows: string[][],
  options?: { startY?: number; rowHeight?: number; headerBg?: string; altRowBg?: string; fontSize?: number }
): number {
  const rowHeight = options?.rowHeight ?? 20;
  const headerBg = options?.headerBg ?? "#1a2332";
  const altRowBg = options?.altRowBg ?? "#f5f5f5";
  const fontSize = options?.fontSize ?? 8;
  let y = options?.startY ?? doc.y;

  // Header row
  doc.rect(MARGIN, y, USABLE_W, rowHeight).fill(headerBg);
  let cx = MARGIN;
  for (const h of headers) {
    const align = h.align ?? "left";
    doc.fontSize(fontSize).fillColor("#ffffff").text(h.label, cx + 4, y + 5, { width: h.width - 8, align });
    cx += h.width;
  }
  y += rowHeight;

  // Data rows
  for (let r = 0; r < rows.length; r++) {
    if (y + rowHeight > FOOTER_Y - 20) {
      doc.addPage();
      y = MARGIN;
      // Redraw header on new page
      doc.rect(MARGIN, y, USABLE_W, rowHeight).fill(headerBg);
      cx = MARGIN;
      for (const h of headers) {
        const align = h.align ?? "left";
        doc.fontSize(fontSize).fillColor("#ffffff").text(h.label, cx + 4, y + 5, { width: h.width - 8, align });
        cx += h.width;
      }
      y += rowHeight;
    }

    const bg = r % 2 === 0 ? "#ffffff" : altRowBg;
    doc.rect(MARGIN, y, USABLE_W, rowHeight).fill(bg);

    cx = MARGIN;
    for (let c = 0; c < headers.length; c++) {
      const align = headers[c].align ?? "left";
      const cellText = rows[r]?.[c] ?? "";
      doc.fontSize(fontSize).fillColor("#222222").text(cellText, cx + 4, y + 5, { width: headers[c].width - 8, align });
      cx += headers[c].width;
    }
    y += rowHeight;
  }

  return y;
}

// ─── Main Export ─────────────────────────────────────────────

export async function generatePdf(
  options: PdfOptions
): Promise<{ buffer: Buffer; sha256Hash: string }> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: MARGIN,
      bufferPages: true,
      info: {
        Title: options.title,
        Author: "CGT-Sync",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => {
      const buffer = Buffer.concat(chunks);
      const sha256Hash = computeSha256(buffer);
      resolve({ buffer, sha256Hash });
    });
    doc.on("error", reject);

    // Title
    doc.moveDown(3);
    doc.fontSize(20).fillColor("#111111").text(options.title, { align: "left" });

    if (options.subtitle) {
      doc.fontSize(12).fillColor("#444444").text(options.subtitle);
    }

    doc.moveDown(1);
    doc
      .moveTo(MARGIN, doc.y)
      .lineTo(PAGE_W - MARGIN, doc.y)
      .strokeColor("#cccccc")
      .stroke();
    doc.moveDown(1);

    // Sections
    for (const section of options.sections) {
      if (doc.y + 40 > FOOTER_Y - 20) {
        doc.addPage();
      }
      doc.fontSize(14).fillColor("#222222").text(section.title);
      doc.moveDown(0.5);

      for (const row of section.rows) {
        if (doc.y + 14 > FOOTER_Y - 20) {
          doc.addPage();
        }
        doc.fontSize(9).fillColor("#666666").text(row.label, { continued: true });
        doc.fillColor("#111111").text(`  ${row.value}`);
      }

      doc.moveDown(1);
    }

    // Inline footer text
    if (options.footer) {
      doc.moveDown(2);
      doc.fontSize(8).fillColor("#999999").text(options.footer, { align: "center" });
    }

    // Generated-by
    if (options.generatedBy) {
      doc
        .fontSize(7)
        .fillColor("#aaaaaa")
        .text(`Generated by: ${options.generatedBy}`, MARGIN, doc.page.height - MARGIN);
    }

    // ──── Header / Footer pass on every page ────
    const generatedAt = new Date().toISOString();
    const pageRange = doc.bufferedPageRange();
    const totalPages = pageRange.count;

    for (let i = 0; i < totalPages; i++) {
      doc.switchToPage(i);

      // Header
      let headerLeftX = MARGIN;
      if (options.logoBuffer) {
        try {
          doc.image(options.logoBuffer, MARGIN, 12, { width: 24 });
          headerLeftX = MARGIN + 30;
        } catch {
          // skip logo on error
        }
      }

      const orgLabel = options.orgName ?? "CGT-Sync";
      doc.fontSize(8).fillColor("#666666").text(orgLabel, headerLeftX, 18, { width: USABLE_W / 3 });
      doc.fontSize(8).fillColor("#666666").text(options.title, MARGIN + USABLE_W / 3, 18, { width: USABLE_W / 3, align: "center" });
      doc.fontSize(8).fillColor("#666666").text("Confidential", MARGIN + (2 * USABLE_W) / 3, 18, { width: USABLE_W / 3, align: "right" });

      // Footer
      doc.moveTo(MARGIN, FOOTER_Y - 5).lineTo(PAGE_W - MARGIN, FOOTER_Y - 5).strokeColor("#cccccc").stroke();
      doc.fontSize(7).fillColor("#999999").text(
        `Page ${i + 1} of ${totalPages}`,
        MARGIN,
        FOOTER_Y,
        { width: USABLE_W / 3 }
      );
      doc.fontSize(7).fillColor("#999999").text(
        generatedAt.split("T")[0],
        MARGIN + USABLE_W / 3,
        FOOTER_Y,
        { width: USABLE_W / 3, align: "center" }
      );
      doc.fontSize(7).fillColor("#999999").text(
        "CGT-Sync",
        MARGIN + (2 * USABLE_W) / 3,
        FOOTER_Y,
        { width: USABLE_W / 3, align: "right" }
      );
    }

    doc.end();
  });
}
