import PDFDocument from "pdfkit";
import { computeSha256 } from "./storage";

interface PdfSection {
  title: string;
  rows: { label: string; value: string }[];
}

interface PdfOptions {
  title: string;
  subtitle?: string;
  generatedBy?: string;
  sections: PdfSection[];
  footer?: string;
}

/**
 * Generate a PDF document server-side and return the buffer + hash.
 * Used for Baseline Packs, Change Ledger Packs, Invoice Review Packs,
 * Dispute Packets, and Weekly Governance Packs.
 */
export async function generatePdf(
  options: PdfOptions
): Promise<{ buffer: Buffer; sha256Hash: string }> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Title: options.title,
        Author: "CGT-Sync",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => {
      const buffer = Buffer.concat(chunks);
      const sha256Hash = computeSha256(buffer);
      resolve({ buffer, sha256Hash });
    });
    doc.on("error", reject);

    // Header
    doc
      .fontSize(8)
      .fillColor("#666666")
      .text("CGT-Sync | Confidential", 50, 30);

    doc
      .fontSize(8)
      .text(
        `Generated: ${new Date().toISOString()}`,
        50,
        30,
        { align: "right" }
      );

    // Title
    doc.moveDown(2);
    doc.fontSize(20).fillColor("#111111").text(options.title, { align: "left" });

    if (options.subtitle) {
      doc.fontSize(12).fillColor("#444444").text(options.subtitle);
    }

    doc.moveDown(1);
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor("#cccccc")
      .stroke();
    doc.moveDown(1);

    // Sections
    for (const section of options.sections) {
      doc.fontSize(14).fillColor("#222222").text(section.title);
      doc.moveDown(0.5);

      for (const row of section.rows) {
        doc.fontSize(9).fillColor("#666666").text(row.label, { continued: true });
        doc.fillColor("#111111").text(`  ${row.value}`);
      }

      doc.moveDown(1);
    }

    // Footer
    if (options.footer) {
      doc.moveDown(2);
      doc.fontSize(8).fillColor("#999999").text(options.footer, { align: "center" });
    }

    // Generated-by
    if (options.generatedBy) {
      doc
        .fontSize(7)
        .fillColor("#aaaaaa")
        .text(`Generated by: ${options.generatedBy}`, 50, doc.page.height - 50);
    }

    doc.end();
  });
}
