-- Rename extraction EventAction values
ALTER TYPE "EventAction" RENAME VALUE 'EXTRACTION_STARTED' TO 'EXTRACTION_JOB_CREATED';
ALTER TYPE "EventAction" RENAME VALUE 'EXTRACTION_COMPLETED' TO 'EXTRACTION_JOB_SUCCEEDED';
ALTER TYPE "EventAction" RENAME VALUE 'EXTRACTION_FAILED' TO 'EXTRACTION_JOB_FAILED';
ALTER TYPE "EventAction" RENAME VALUE 'EXTRACTION_APPLIED' TO 'EXTRACTION_JOB_APPLIED';
