/**
 * Build-time script: parse prisma/schema.prisma and emit src/generated/table-map.ts
 *
 * Run: npx tsx scripts/generate-table-map.ts
 * Called automatically by `npm run build`.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, "..");
const SCHEMA_PATH = path.join(ROOT, "prisma/schema.prisma");
const OUT_PATH = path.join(ROOT, "src/generated/table-map.ts");

const schemaText = fs.readFileSync(SCHEMA_PATH, "utf-8");

interface Mapping {
  modelName: string;
  tableName: string;
}

const mappings: Mapping[] = [];
// Use [\s\S]*? (lazy) with \n} anchor — handles } inside @default("{}") strings
const modelRe = /^model\s+(\w+)\s*\{([\s\S]*?)\n\}/gm;
let match: RegExpExecArray | null;

while ((match = modelRe.exec(schemaText)) !== null) {
  const modelName = match[1];
  const body = match[2];
  const mapMatch = body.match(/@@map\(\s*"([^"]+)"\s*\)/);
  const tableName = mapMatch ? mapMatch[1] : modelName.toLowerCase() + "s";
  mappings.push({ modelName, tableName });
}

const lines = [
  "// AUTO-GENERATED by scripts/generate-table-map.ts — do not edit manually.",
  `// Generated at: ${new Date().toISOString()}`,
  "",
  "export const MODEL_TABLE_MAPPINGS = [",
  ...mappings.map(
    (m) => `  { modelName: "${m.modelName}", tableName: "${m.tableName}" },`
  ),
  "] as const;",
  "",
  "export type ModelTableMapping = (typeof MODEL_TABLE_MAPPINGS)[number];",
  "",
  "export const EXPECTED_TABLES = MODEL_TABLE_MAPPINGS.map((m) => m.tableName);",
  "",
];

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, lines.join("\n"), "utf-8");

console.log(
  `Generated ${OUT_PATH} with ${mappings.length} model→table mappings.`
);
